name: Testing

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: pytorch/pytorch:2.6.0-cuda12.6-cudnn9-devel

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run tests
              run: |
                python -m unittest tests/test.py -v
            
            - uses: actions/upload-artifact@v2
              with:
                name: test-results
                path: test-results.xml
                retention-days: 1